import type { Metadata } from "next";
import "./globals.css";

import { geistSans, geistMono } from "@/lib/fonts";

export const metadata: Metadata = {
    title: "Crow475",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex min-h-full w-full flex-col overflow-x-hidden">
                {children}
            </body>
        </html>
    );
}
